### ISSUE TITLE
Nothing captured!

### ISSUE THREAD

**Issue by lephuhung** [Eltion/Facebook-SSL-Pinning-Bypass#12]
Android: AVD api 28  (pixel 4 android virtual device)
Facebook downloaded: arm
Device: macbook M1
i installed patched apk on android virutal device, capture request by burp proxy but nothing captured.
Log ADB:
--------- beginning of system
--------- beginning of main
01-14 22:24:01.619  4149  4295 V FACEBOOK_SSL_PINNING_BYPASS: [*][*] Waiting for library...
01-14 22:24:01.621  4149  4295 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Hooked checkTrustedRecursive
01-14 22:24:02.052  4149  4369 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Found libcoldstart.so at: 0x7b685e6000
01-14 22:24:02.055  4149  4369 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
01-14 22:24:02.150  4149  4451 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Patched libcoldstart.so
01-14 22:24:05.386  5129  5190 V FACEBOOK_SSL_PINNING_BYPASS: [*][*] Waiting for library...
01-14 22:24:05.387  5129  5190 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Hooked checkTrustedRecursive
01-14 22:24:05.779  5129  5202 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Found libcoldstart.so at: 0x7b686df000
01-14 22:24:05.793  5129  5202 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
01-14 22:24:05.893  5129  5250 V FACEBOOK_SSL_PINNING_BYPASS: [*][+] Patched libcoldstart.so
Burpsuite error:
<img width="1022" alt="Screenshot 2023-01-14 at 22 30 16" src="https://user-images.githubusercontent.com/20222030/212480019-e34b6ecc-a0bf-413f-9c50-3ef89d9c1a0f.png">

**Comment by Eltion** [comment]
@lephuhung Can you share the full message error from burp?

**Comment by lephuhung** [comment]
> @lephuhung Can you share the full message error from burp?

![Uploading Screenshot 2023-01-14 at 22.42.42.png…]()

**Comment by lephuhung** [comment]
> @lephuhung Can you share the full message error from burp?

<img width="1704" alt="Screenshot 2023-01-14 at 22 42 42" src="https://user-images.githubusercontent.com/20222030/212480513-e4ed67fe-5b79-427b-997c-51fd0fa039a9.png">

**Comment by Eltion** [comment]
As you can see the facebook app uses TLSv1.3 and you either have configured burp to not use TLSv1.3 or you're on a old version of burp that does not support TLSv1.3, so try installing the latest version and it will work :)

**Comment by Eltion** [comment]
I'll consider this resolved. If any problem feel free to reopen he issue.

**Comment by lephuhung** [comment]
thank, it working, but some parameter request i can't not understand, example, can you help me
<img width="660" alt="Screenshot 2023-01-15 222624" src="https://user-images.githubusercontent.com/20222030/212550102-87bdac99-1aff-40ac-897f-b3535d39cdcb.png">

**Comment by Eltion** [comment]
@lephuhung I'm sorry that's out of the scope of this repo. If enough people request that I can look into it :)

**Comment by lephuhung** [comment]
> @lephuhung I'm sorry that's out of the scope of this repo. If enough people request that I can look into it :)

many thank for sharing

**Comment by DerLomo** [comment]
> @lephuhung I'm sorry that's out of the scope of this repo. If enough people request that I can look into it :)

Yeah,I am having the same problem, could you at least tell what's the cause?

> @lephuhung many thank for sharing


Did you found any solution?

**Comment by Forterc** [comment]
gzipped
