### ISSUE TITLE
FACEBOOK LITE

### ISSUE THREAD

**Issue by ghost** [Eltion/Facebook-SSL-Pinning-Bypass#13]
please by pass facebook lite

**Comment by Eltion** [comment]
Currently this is not planned. I've added it into the list of goals in buymeacoffee, if enough people need it I'll do it :)

**Comment by ghost** [comment]
i need it, can you do it for me, i need it please

Pada tanggal Min, 15 Jan 2023 01.22, Eltion Musa ***@***.***>
menulis:

**Comment by ghost** [comment]
i need it, can you do it for me, i need it please
