### ISSUE TITLE
Ads Manager android ssl pinning bypass

### ISSUE THREAD

**Issue by xuan2261** [Eltion/Facebook-SSL-Pinning-Bypass#14]
Hi, can you provide Ads Manager android app ssl pinning bypass ?

**Comment by Eltion** [comment]
@xuan2261 that's outside the scope of this repo. If more people ask about it I may create an open source project.

**Comment by jsxforgit** [comment]
@Eltion i need to

**Comment by xuan2261** [comment]
> @xuan2261 that's outside the scope of this repo. If more people ask about it I may create an open source project.
There are many people who need it. can you create a new repo for it?

**Comment by Mp3playpro** [comment]
Sir please create

**Comment by Mp3playpro** [comment]
Please upload Facebook Lattest patch version

**Comment by shafle** [comment]
i need to
