### ISSUE TITLE
SSL PINNING USING ANDROID 

### ISSUE THREAD

**Issue by dcofficial** [Eltion/Facebook-SSL-Pinning-Bypass#16]
Hy brother i want to use ssl PINNING of Facebook using my Android device without root or can i use rdp how i get full tutorial guide me

**Comment by Eltion** [comment]
You cab follow this guide to catpure the requests using burp:
https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/wiki/Capture-packets-using-Brup-Suite

**Comment by dcofficial** [comment]
Thanks but i want Facebook app ssl

**Comment by Eltion** [comment]
Yes but the same process is for facebook, you just need to download the app from here:
https://github.com/Eltion/Facebook-SSL-Pinning-Bypass/releases/tag/v396.1.0.28.104
