### ISSUE TITLE
how to use it on Facebook Messenger?

### ISSUE THREAD

**Issue by linhere20** [Eltion/Facebook-SSL-Pinning-Bypass#3]
Facebook Messenger `libcoldstart.so`  doesn't have `proxygen::SSLVerification::verifyWithMetrics` method.  Do you have any idea ? thanks

**Comment by kingyyy** [comment]
please help same problem here

**Comment by Eltion** [comment]
I don't plan on checking messenger app. If enough people request it I will consider doing an ssl pinning for it 🙂

**Comment by Eltion** [comment]
@linhere20 , @kingyyy I created a repo for messenger, you can check it here: https://github.com/Eltion/Messenger-SSL-Pinning-Bypass
