### ISSUE TITLE
network is unreachable 

### ISSUE THREAD

**Issue by LPeng111** [Eltion/Facebook-SSL-Pinning-Bypass#4]
Hello, I installed the patched apk([facebook-v373.0.0.31.112-armeabi-v7a]) on my device, and it worked very good.
But when I use burpsuite to intercept(I switched off intercept), the app shows that the network is unreachable.
![image](https://user-images.githubusercontent.com/39934458/181144621-f00daf8d-3280-4a85-81bd-f53b310769b4.png)
![image](https://user-images.githubusercontent.com/39934458/181194560-c16b8f48-a351-4b14-9825-bea4764bcfc1.png)

Could you please tell me what the reason is and how I should solve it?

**Comment by LPeng111** [comment]
![image](https://user-images.githubusercontent.com/39934458/181194485-266cf468-1442-491d-b074-668670af8715.png)

**Comment by Eltion** [comment]
Can you show me the logs from running.
```
adb logcat -s "FACEBOOK_SSL_PINNING_BYPASS:V"
```

**Comment by LPeng111** [comment]
![image](https://user-images.githubusercontent.com/39934458/186115804-7c9e0134-e76e-495e-8eaa-1713f8172ea8.png)

**Comment by melissaattack** [comment]
> ![image](https://user-images.githubusercontent.com/39934458/186115804-7c9e0134-e76e-495e-8eaa-1713f8172ea8.png)

I also got the same error!

**Comment by melissaattack** [comment]
![image](https://user-images.githubusercontent.com/82698334/194722041-02473437-b0ad-4969-aa6b-b13fb3502a42.png)
[ASUS_Z01QD::com.facebook.katana ]-> [*][+] Hooked checkTrustedRecursive
[*][+] Found libcoldstart.so at: 0xd0614000
[*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE

**Comment by demon071** [comment]
Facebook app says no internet connection

**Comment by guytshewlir** [comment]
> ![image](https://user-images.githubusercontent.com/82698334/194722041-02473437-b0ad-4969-aa6b-b13fb3502a42.png) [ASUS_Z01QD::com.facebook.katana ]-> [_][+] Hooked checkTrustedRecursive [_][+] Found libcoldstart.so at: 0xd0614000 [*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE

I'm facing the same problem, @Eltion could you help us, please ?

**Comment by Eltion** [comment]
@guytshewlir , I've updated the script to do one additional patch, currently only for arm64 and x86.
I've tested it on the latest version `v394.0.0.50.107` and it's working :) . Let me know if you have any problems
