### ISSUE TITLE
Not work with file packed, work with file not pack

### ISSUE THREAD

**Issue by nguyentuan3691** [Eltion/Facebook-SSL-Pinning-Bypass#7]
When use file packed then show error
[*][*] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
[*][*] Failed tp hook function: X509_verify_cert
Error: libcoldstart.so: unable to find export 'X509_verify_cert'

i'm try with file new in google play then success(hook working) but using fiddler then can't handshake(can't trust cer).

**Comment by Eltion** [comment]
Please use a different proxy tool. One that supports TLS1.3

**Comment by demon071** [comment]
> When use file packed then show error [_][_] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE [_][_] Failed tp hook function: X509_verify_cert Error: libcoldstart.so: unable to find export 'X509_verify_cert'
> 
> i'm try with file new in google play then success(hook working) but using fiddler then can't handshake(can't trust cer).

làm được chưa bác
