### ISSUE TITLE
even after removing facebook app using adb shell..can't install patched apk

### ISSUE THREAD

**Issue by UxplnJDK** [Eltion/Facebook-SSL-Pinning-Bypass#8]
even after removing facebook app using adb shell..can't install patched apk ..While downloading and installing it says "The package conflicts with the existing package with the same name".. Is there is solution for this/way to install this patched apk .

**Comment by Eltion** [comment]
Hi @UxplnJDK. That message actually means that the previous facebook app is not removed!
